apiVersion: v1
kind: Service
metadata:
  name: data-app
spec:
  ports:
    - port: 3000
  type: LoadBalancer
  selector:
    app: data-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-app
spec:
  selector:
    matchLabels:
      app: data-app
  template:
    metadata:
      labels:
        app: data-app
    spec:
      containers:
        - name: data-app
          image: a1liu/data-app
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-configuration
