package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"a1liu.com/data/api/dbutil"
	"a1liu.com/data/api/graph"
)

type mutationResolver struct{ *Resolver }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

func (r *mutationResolver) MigrateDb(ctx context.Context) (bool, error) {
	rctx := ResCtx(ctx)

	conn, err := rctx.Pool.Acquire(ctx)
	if err != nil {
		return false, err
	}
	defer conn.Release()

	err = dbutil.MigrateDatabase(ctx, conn)
	return err == nil, err
}
