package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"a1liu.com/data/api/graph"
	"a1liu.com/data/api/model"
)

type mutationResolver struct{ *Resolver }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Dummy is the resolver for the dummy field.
func (r *mutationResolver) Dummy(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Dummy - dummy"))
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
