apiVersion: v1
kind: Service
metadata:
  name: gql-api
spec:
  ports:
    - port: 8080
  type: LoadBalancer
  selector:
    app: gql-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-api
spec:
  selector:
    matchLabels:
      app: gql-api
  template:
    metadata:
      labels:
        app: gql-api
    spec:
      containers:
        - name: gql-api
          image: a1liu/gql-api
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-configuration
