apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.name" . }}-configuration
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
