apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: postgres
  type: ClusterIP
  selector:
    {{- include "postgres.labels" . | nindent 4 }}
