apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
  selector:
    {{- include "web.labels" . | nindent 4 }}
