apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  selector:
    {{- include "api.labels" . | nindent 4 }}
