name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: pnpm-lock.yaml
          cache: pnpm

      - name: Install packages
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Push prisma schema
        run: pnpm exec prisma db push --accept-data-loss

      - name: Run tests
        run: pnpm test
