apiVersion: skaffold/v1
kind: Config
build:
  local:
    useBuildkit: true
    push: false # shouldn't technically be necessary
  artifacts:
    - image: a1liu/webapp
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - infra/webapp.yml
